# This is a basic workflow to help you get started with Actions

name: Acorn test suite

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        COMPILER: [gcc, clang]
        FLAGS: ["", "--debug", "--cc-opt=\"-O2\"", "--cc-opt=\"-O3\"", "--cc-opt=-pedantic"]
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: configure build
      run: |
        if [ "${{matrix.os}}" = "macos-latest" ]; then
          brew install capstone
        else
          sudo apt-get install libcapstone-dev;
        fi;
        ./configure --cc=${{matrix.COMPILER}} --ld=${{matrix.LINKER}} \
                    ${{matrix.FLAGS}}

    - name: build and test
      run: make
